language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t smokegrenade/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true smokegrenade/react-test npm test -- --coverage

after_success:
    - docker build -t smokegrenade/multi-client ./client
    - docker build -t smokegrenade/multi-nginx ./nginx
    - docker build -t smokegrenade/multi-server ./server
    - docker build -t smokegrenade/multi-worker ./worker
    #Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub

    - docker push smokegrenade/multi-client
    - docker push smokegrenade/multi-nginx
    - docker push smokegrenade/multi-server
    - docker push smokegrenade/multi-worker



deploy:
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-898879965557
    bucket_path: docker-multi
    on:
        branch: master

